name: iOS workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          npm install
          npx expo install

      - name: Run expo doctor
        run: |
          npx expo-doctor

      - name: Run build
        run: |
          npx expo run:ios
